function make_all(s_MdlName,sTarget)
%make_all is the building function that executes the mk-file generated by 
%Mathworks EmbeddedCoder in order to generate a hex-file for
%downloading onto your Target. In case you have more directories below your
%make_root all these directories need to have their own mk-file.
%
%make_all(s_MdlName[,sTarget])
%
%In: 
%s_MdlName:  Name of the Model without extention
%sTarget:    any of 'TTC508','TTC510', 'TTC520', 'TTC540', 'TTC580','TTC590','TTC590E','TTC510_GEN2','TTC520_GEN2','TTC540_GEN2','TTC580_GEN2'
%            default: 'TTC580_GEN2'
%

%init
sBUILD = 'build';
cALLOWED_TTC5XX = {'TTC508','TTC510', 'TTC520', 'TTC540', 'TTC580','TTC590','TTC590E','TTC510_GEN2','TTC520_GEN2','TTC540_GEN2','TTC580_GEN2'}; %valid HY-TTC580 variants

if nargin < 1
    error('Please specify the name of the model to make without extention')
end
if nargin < 2
    TARGET = 'TTC580_GEN2';
    disp([char(13),'No specific target specified, building default target : ',TARGET,char(13)]);
else
    TARGET = sTarget;
end

%checks:
if ~(isa(s_MdlName,'char'))
    error('Please specify the name of the model as a string')
end
if ~ismember(TARGET,cALLOWED_TTC5XX)
    error(['The target given as %s may only have one of the following values \n',cALLOWED_TTC5XX{:},'\n'],TARGET);
end

%make all objects
all_mk = rdir([pwd,'\**\*.mk']);
for i = 1:length(all_mk)
    [dummy,s_PartMdlName] = fileparts(all_mk(i).name);
    make_obj(s_PartMdlName,TARGET);
end

%prepare OBJ file
%path_mdl = fileparts(all_mdl(1).name);
%s_full_MdlErtDir = [path_mdl,'\',s_MdlErtDir];
all_mdl_mk = rdir([pwd,'\**\',s_MdlName,'.mk']);
s_full_MdlErtDir = extract_path(all_mdl_mk,s_MdlName);

sOBJ_DEF_FILE = 'C:\TTTech\Environment_TTC580\build\link_tmp.cmd';
fid = fopen(sOBJ_DEF_FILE,'w');
if (fid == -1)
    fprintf('Warning make_all(): unable to open  file %s\n',sOBJ_DEF_FILE)
    return
end

s_ActDir = pwd;
[b_success,dummy]=mkdir(s_full_MdlErtDir,sBUILD); 
if ~b_success
    error('mkdir: failed to make direcotry "build"');
end

%find all objects
all_obj = rdir ([pwd,'\**\*.obj']);
cd(s_full_MdlErtDir);
for i=1:length(all_obj)
    if (isempty(findstr(all_obj(i).name,'\sim\'))) && ...
            (isempty(findstr(all_obj(i).name,'_main.'))) && ...
            (isempty(findstr(all_obj(i).name,'_sfprj'))) && ...
            (isempty(findstr(all_obj(i).name,'_jitprj'))) && ...
            (isempty(findstr(all_obj(i).name,[s_full_MdlErtDir,'\build']))) %don't recopy on itself
        % write extended linear address record
        %fprintf(fid,'%s\n',['IOLIB580_OBJ += ',all_obj(i).name]);
        [dummy,filename] = fileparts(all_obj(i).name);
        dir_filename_ext = [sBUILD,'\',filename,'.obj'];
        %fprintf(fid,'%s\n',['IOLIB580_OBJ += ',dir_filename_ext]);
        fprintf(fid,'%s\n',dir_filename_ext);
        if exist(['.\',dir_filename_ext]) 
            warning(['File already exist: ',dir_filename_ext,': multiple occurences of the same file in the build tree. Manual check on consistency necessary !']);
        end
        copyfile(all_obj(i).name,sBUILD);
    end
end

fclose(fid);

sWhichMake = ['"',which('make.exe'),'"'];
make_file=dir('*.mk');  %This file expands the tag <MATLABROOT>
sWhichMakeFile = ['"',make_file.name,'"'];
%not necessary: sMatlabRoot = ['"',matlabroot,'"']; because of tag <MATLABROOT> in ert_TTC580.tmf

s_cmd = (['!',sWhichMake,' TARGET=',TARGET,' --makefile=',sWhichMakeFile,' all']);   %don't clean because of copied obj-files
disp(s_cmd);
eval(s_cmd);

%rename hex file from app.hex to <ModelName>.hex
try
    sHex_file_orig = ['.\build\','app.hex'];
    sHex_file_new =  ['.\build\',s_MdlName,'.hex'];
    if exist(sHex_file_orig,'file')
        movefile(sHex_file_orig,sHex_file_new);
    end
end
cd(s_ActDir)

%%%%%%%%%%%%%%%%%%%%%%%%%%%
function s_ModelPath=extract_path(all_mdl,s_MdlName)
if isempty(all_mdl)
    error(['Make file not found for ',s_MdlName,'.slx or ',s_MdlName,'.mdl']);
elseif length(all_mdl) ~= 1
    error([s_MdlName,' not unique: multiple code found, please delete the obsolte one']);
else %OK
    s_ModelPath = fileparts(all_mdl(1).name);
end


